#!/usr/bin/env bash
# Template: 1.0.0
#######################################
# Toolbox64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

export TOOLBOX64_BASHLIB64="${TOOLBOX64_BASHLIB64:-/usr/local/lib/bashlib64.bash}"
# shellcheck disable=SC1090
source "$TOOLBOX64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${TOOLBOX64_BASHLIB64})" && exit 1; }

#
# Globals
#

export TOOLBOX64_DEBUG="${TOOLBOX64_DEBUG:-}"

#
# Functions
#

#######################################
# Install application packages
#
# Arguments:
#   None
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function tb64_install() {
  bl64_dbg_app_show_function

  # X_CODE_PLACEHOLDER_X
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function tb64_initialize() {
  bl64_dbg_app_show_function

  # delete-me # Update OS list as needed
  bl64_os_match "${BL64_OS_ALP}" || {
    bl64_check_alert_unsupported
    return $?
  }
  bl64_check_privilege_root &&
    bl64_pkg_setup ||
    return $?
}

#
# Main
#

declare tb64_task_title='Install package: X_PACKAGE_NAME_X'
declare -i tb64_status=0

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$tb64_task_title"

[[ -n "$TOOLBOX64_DEBUG" ]] && bl64_dbg_lib_enable
tb64_initialize &&
  tb64_install
tb64_status=$?

bl64_msg_show_batch_finish "$tb64_status" "$tb64_task_title"
exit $tb64_status
