#!/usr/bin/env bash
#
# Run test-cases
#
# * Test cases are done using bats-core
# * TestManSH is used to manage test environment
# * Tests are located in the default path "test/batscore"
# * Template Version: v1.0.0
#

# shellcheck source=SCRIPTDIR/dev-set
source ./bin/dev-set || exit 1

# DeleteMe # Build and test distributable. Remove if not needed
./bin/dev-build &&
  ./lib/testmansh -b -o -e "$X_PROJECT_NAME_DEV_CAPS_X_TEST_CONTAINER"

# DeleteMe # Test code. Remove if not needed
# ./lib/testmansh -b -o -e "$X_PROJECT_NAME_DEV_CAPS_X_TEST_CONTAINER"
