#!/usr/bin/env bash
#
# Lint shell source code
#
# * Use to lint shell source code
# * Check is done using shellcheck
# * TestManSH is used to manage linting environment
# * Template Version: v1.0.0
#

# shellcheck source=SCRIPTDIR/dev-set
source ./bin/dev-set || exit 1

# DeleteMe # Build and Lint distributable. Remove if not needed
./bin/dev-build &&
  ./lib/testmansh -t -o -c "$X_PROJECT_NAME_DEV_CAPS_X_BUILD"

# DeleteMe # Lint source. Remove if not needed
# ./lib/testmansh -t -o -c "$X_PROJECT_NAME_DEV_CAPS_X_SRC"
