#!/usr/bin/env bash
# Template: 1.0.0
#######################################
# Container64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export CNT64_DEBUG="${CNT64_DEBUG:-}"
# X_CODE_PLACEHOLDER_1_X

# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

# X_CODE_PLACEHOLDER_2_X

#
# Functions
#

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function cnt64_X_APP_NAME_X_install() {
  bl64_dbg_app_show_function
  # X_CODE_PLACEHOLDER_3_X
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_X_APP_NAME_X_initialize() {
  bl64_dbg_app_show_function
  # X_CODE_PLACEHOLDER_4_X
}

#
# Main
#

declare cnt64_X_APP_NAME_X_installer_description='Install application: X_APP_FULL_NAME_X'
declare -i cnt64_X_APP_NAME_X_status=0

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_X_APP_NAME_X_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
cnt64_X_APP_NAME_X_initialize &&
  cnt64_X_APP_NAME_X_install
cnt64_X_APP_NAME_X_status=$?

bl64_msg_show_batch_finish "$cnt64_X_APP_NAME_X_status" "$cnt64_X_APP_NAME_X_installer_description"
exit $cnt64_X_APP_NAME_X_status
